{"name": "test_update_customer_status_existing", "status": "broken", "statusDetails": {"message": "NameError: name 'generate_random_string' is not defined", "trace": "@pytest.fixture\n    def test_customer_data():\n        return {\n            \"firstname\": \"Test\",\n            \"lastname\": \"User\",\n>           \"email\": generate_random_email(),\n            \"telephone\": generate_random_phone(),\n            \"password\": \"hashed_pass\",  # Предполагем, что пароль уже хэширован\n            \"newsletter\": 0,\n            \"status\": 1,\n        }\n\ntests/test_customer.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def generate_random_email():\n>       return f\"{generate_random_string()}@example.com\"\nE       NameError: name 'generate_random_string' is not defined\n\ntests/test_customer.py:14: NameError"}, "start": 1746287017710, "stop": 1746287017710, "uuid": "37a9a307-502a-4ff7-a780-567b5e46f10e", "historyId": "81404541623e5b1bc6b95f2b86cd6c6e", "testCaseId": "81404541623e5b1bc6b95f2b86cd6c6e", "fullName": "tests.test_customer#test_update_customer_status_existing", "labels": [{"name": "severity", "value": "normal"}, {"name": "story", "value": "Обновление статуса клиента"}, {"name": "feature", "value": "Клиенты"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_customer"}, {"name": "host", "value": "MacBook-Air-2.local"}, {"name": "thread", "value": "14632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_customer"}]}