{"name": "test_create_customer_and_verify_by_id", "status": "broken", "statusDetails": {"message": "NameError: name 'generate_random_string' is not defined", "trace": "@pytest.fixture\n    def test_customer_data():\n        return {\n            \"firstname\": \"Test\",\n            \"lastname\": \"User\",\n>           \"email\": generate_random_email(),\n            \"telephone\": generate_random_phone(),\n            \"password\": \"hashed_pass\",  # Предполагем, что пароль уже хэширован\n            \"newsletter\": 0,\n            \"status\": 1,\n        }\n\ntests/test_customer.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def generate_random_email():\n>       return f\"{generate_random_string()}@example.com\"\nE       NameError: name 'generate_random_string' is not defined\n\ntests/test_customer.py:14: NameError"}, "start": 1746287017520, "stop": 1746287017520, "uuid": "90baaa50-2a69-409a-8179-1ec91c0f2948", "historyId": "097d1764a431dd8396e9eced2dc71f8c", "testCaseId": "097d1764a431dd8396e9eced2dc71f8c", "fullName": "tests.test_customer#test_create_customer_and_verify_by_id", "labels": [{"name": "story", "value": "Создание клиента"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "Клиенты"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_customer"}, {"name": "host", "value": "MacBook-Air-2.local"}, {"name": "thread", "value": "14632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_customer"}]}